Algoritmo "Exemplo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/7/2021
Var
// Seção de Declarações das variáveis 
n1,n2,soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um numero")
leia (n1)
soma <-n1+n2
escreva ("Digite outro numero")
leia (n2)
escreva ("A soma dos dois numeros è ",soma)

Fimalgoritmo