Algoritmo "Exemplo 002"
//DESENVOLVER UM ALGORITMO QUE PEÇA AO USUÁRIO
//O SEU NOME E A SUA ALTURA, LOGO DEPOIS
//PULE 2 LINHAS E MOSTRE NA TELA O NOME E A ALTURA.
Var
nome:caracter
altura:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Qual seu nome?")
   leia (nome)
   escreva("Qual a sua altura?")
   leia (altura)
   escrevaL ("")
   escreval ("")
   escreva ("Seu nome é ", nome, " e a sua altura é ", altura)


Fimalgoritmo